ideasboardwithcss/config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :comments
  end

  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end

  resources :users do
    resources :posts do
      resources :comments
    end
  end
  get 'home/index'
  get 'home/viewAll'
  post '/home/viewAll'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]

  root "home#index"

end

ideasboardwithcss/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ideasboardwithcss/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

ideasboardwithcss/app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  belongs_to :user
  acts_as_votable

  def score
    self.get_upvotes.size - self.get_downvotes.size
  end

  def self.search(search)
    if search
      where('title ILIKE ?', "%#{search}%")

    else
      all
    end
  end


end

ideasboardwithcss/app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.image = auth.info.image
      user.oauth_refresh_token = auth.credentials.refresh_token if auth.credentials.refresh_token
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

end

ideasboardwithcss/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

 # rescue_from CanCan::AccessDenied do |exception|
  #  flash[:error] = "Access denied."
   # redirect_to root_url
  #end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


end

ideasboardwithcss/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comments
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET posts/1/comments
  def index
    @comments = @post.comments
  end

  # GET posts/1/comments/1
  def show
  end

  # GET posts/1/comments/new
  def new
    @comment = @post.comments.build
  end

  # GET posts/1/comments/1/edit
  def edit
  end

  # POST posts/1/comments
  def create
    @comment = @post.comments.build(comment_params)

    if @comment.save
      #redirect_to([@comment.post, @comment], notice: 'Comment was successfully created.')
      #return a json data to notify user that comment is added.
      # and also return the added comment.
      render :json => [@comment,@comment.user.image,@comment.user.name]
    else
      render action: 'new'
    end
  end

  # PUT posts/1/comments/1
  def update
    if @comment.update_attributes(comment_params)
      redirect_to([@comment.post, @comment], notice: 'Comment was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE posts/1/comments/1
  def destroy
    @comment.destroy

    redirect_to post_comments_url(@post)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comments
      @post = Post.find(params[:post_id])
    end

    def set_comment
      @comment = @post.comments.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def comment_params
      params.require(:comment).permit(:comment,:user_id)
    end
end

ideasboardwithcss/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def viewAll
    @posts= Post.all.search(params[:search]).order(created_at: :desc).paginate(:per_page => 5, :page => params[:page])
  end
end

ideasboardwithcss/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_posts, only: [:create]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET users/1/posts
  def index
    @posts = @user.posts

  end

  # GET users/1/posts/1
  def show
  end

  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    render :json => [@post.get_upvotes.size,@post.get_downvotes.size,@post.id]

  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_by current_user
    render :json => [@post.get_upvotes.size,@post.get_downvotes.size,@post.id]


  end

  # GET users/1/posts/new
  def new
    @post = @user.posts.build
  end

  # GET users/1/posts/1/edit
  def edit
  end

  # POST users/1/posts
  def create
    @post = @user.posts.build(post_params)

    if @post.save
      #redirect_to([@post.user, @post], notice: 'Post was successfully created.')
      render json: @post
    else
      render action: 'new'
    end
  end

  # PUT users/1/posts/1
  def update
    if @post.update_attributes(post_params)
      redirect_to([@post.user, @post], notice: 'Post was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE users/1/posts/1
  def destroy
    @post.destroy

    redirect_to user_posts_url(@user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_posts
      @user = User.find(params[:user_id])
    end

    def set_post
      @post = @user.posts.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

ideasboardwithcss/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to home_viewAll_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

ideasboardwithcss/app/helpers/application_helper.rb
module ApplicationHelper
end

ideasboardwithcss/app/helpers/comments_helper.rb
module CommentsHelper
end

ideasboardwithcss/app/helpers/home_helper.rb
module HomeHelper
end

ideasboardwithcss/app/helpers/posts_helper.rb
module PostsHelper
end

ideasboardwithcss/app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

ideasboardwithcss/app/views/comments/_form.html.erb
<%= form_for([@comment.post, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ideasboardwithcss/app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', [@comment.post, @comment] %> |
<%= link_to 'Back', post_comments_path(@comment.post) %>

ideasboardwithcss/app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.comment %></td>
    <td><%= link_to 'Show', [comment.post, comment] %></td>
    <td><%= link_to 'Edit', edit_post_comment_path(comment.post, comment) %></td>
    <td><%= link_to 'Destroy', [comment.post, comment], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_post_comment_path(params[:post_id]) %>

ideasboardwithcss/app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', post_comments_path(@comment.post) %>

ideasboardwithcss/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Comment:</b>
  <%= @comment.comment %>
</p>


<%= link_to 'Edit', edit_post_comment_path(@comment.post, @comment) %> |
<%= link_to 'Back', post_comments_path(@comment.post) %>

ideasboardwithcss/app/views/home/index.html.erb
<link rel="stylesheet" href="w3.css">
<style>
  .mySlides {display:none}
  .w3-left, .w3-right, .w3-badge {cursor:pointer}
  .w3-badge {height:13px;width:13px;padding:0}
</style>
<style>
  .mySlides {display:none}
  .w3-left, .w3-right, .w3-badge {cursor:pointer}
  .w3-badge {height:13px;width:13px;padding:0}
</style>
<br>
<hr>
<br>
<div class="w3-content w3-display-container" style="max-width:800px ; max-height:1000px">
  <img class="mySlides " src="Elon-Musk.jpg" style="height:550px;width:800px">
  <img class="mySlides " src="Bill-Gates.jpg" style="height:550px;width:800px">
  <img class="mySlides " src="Mark.jpg" style="height:550px;width:800px">
  <div class="w3-center w3-section w3-large w3-text-white w3-display-bottommiddle" style="width:100%">
    <div class="w3-left w3-padding-left w3-hover-text-khaki" onclick="plusDivs(-1)">&#10094;</div>
    <div class="w3-right w3-padding-right w3-hover-text-khaki" onclick="plusDivs(1)">&#10095;</div>
    <span class="w3-badge demo w3-border w3-transparent w3-hover-white" onclick="currentDiv(1)"></span>
    <span class="w3-badge demo w3-border w3-transparent w3-hover-white" onclick="currentDiv(2)"></span>
    <span class="w3-badge demo w3-border w3-transparent w3-hover-white" onclick="currentDiv(3)"></span>
  </div>
</div>




  <script>
  var myIndex = 0;
  carousel();

  function carousel() {
    var i;
    var x = document.getElementsByClassName("mySlides");
    for (i = 0; i < x.length; i++) {
      x[i].style.display = "none";
    }
    myIndex++;
    if (myIndex > x.length) {myIndex = 1}
    x[myIndex-1].style.display = "block";
    setTimeout(carousel, 4000); // Change image every 4 seconds
  }
</script>
<script>
  var slideIndex = 1;
  showDivs(slideIndex);

  function plusDivs(n) {
    showDivs(slideIndex += n);
  }

  function currentDiv(n) {
    showDivs(slideIndex = n);
  }

  function showDivs(n) {
    var i;
    var x = document.getElementsByClassName("mySlides");
    var dots = document.getElementsByClassName("demo");
    if (n > x.length) {slideIndex = 1}
    if (n < 1) {slideIndex = x.length}
    for (i = 0; i < x.length; i++) {
      x[i].style.display = "none";
    }
    for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" w3-white", "");
    }
    x[slideIndex-1].style.display = "block";
    dots[slideIndex-1].className += " w3-white";
  }
</script>



<br>
<br><hr>
<br>


<div class="center jumbotron" >
  <span class="image-block"><h1>Kick Start your Ideas!
</h1>
    <br>

   <h4> An exclusive discussion board to share ideas.</h4>




  <% if !current_user %>
  <%= link_to "Sign in now!", "/auth/google_oauth2", class: "btn btn-lg btn-primary" %>
      <%else%>
  <%= link_to "Share your ideas!", "/home/viewAll", class: "btn btn-lg btn-primary" %>
  <%end%>

</span>
</div>

ideasboardwithcss/app/views/home/viewAll.html.erb
<!-- Top Banner -->
<section class="headerofbody card-holder">
<!-- br tags for placements of the first card with respect to top banner -->
<br>
  <br>
  <br>
  <br>
  <br>



<!-- Cards start here , First card is Share your thoughts card --->
<section class="card beauty">
<h1 style="color: black">Share your thoughts</h1>

<form class="new_post" id="new_post" action="/users/<%=current_user.id%>/posts" accept-charset="UTF-8" method="post" data-remote="true">
  <input name="utf8" type="hidden" value="&#x2713;" />
  <input type="hidden" name="authenticity_token" value="NASbMiQlGr8iSFj2oGQZQLhRyiOx2A6JZsdZKbc/y22UJgW9ZZZIogfzwpF/se/cRuFz0pW/R9DNUdihLbw1tQ==" />
  <div class="field">
    <label for="post_title" style="color: black" >Title</label><br />
    <input type="text" name="post[title]" id="post_title" placeholder="Give a title to your idea..."/>
  </div>
  <div class="field">
    <label for="post_content" style="color: black">Content</label><br />
    <textarea name="post[content]" id="post_content" style="height: 120px;" placeholder="Express yourself...">
</textarea>
  </div>
  <div class="btn btn-lg ">
    <input type="submit" name="commit" value="Create Post" data-disable-with="Create Post" />
  </div>
</form>
</section>
<!-- horizontal ruler after share your thoughts card -->
<hr>
<!-- posts cards start here -->

<% @posts.each do |post| %>
<section class="card">
  <tr>
    <td><h3><u><%= post.title %> - <%= post.user.name%></u></h3></td>
    <span class="timestamp">
      Posted <%= time_ago_in_words(post.created_at) %> ago.
    </span>
      <td><h4><%= post.content %></h4></td>
    <span class="thumb" >
    <%= link_to like_post_path(post), method: :put,remote: true do %>
        <font size="20" >&#x1F44D;</font>
        <span class="voteup" id ="<%=post.id%>"><%= post.get_upvotes.size %></span>
    <% end %>
    <%= link_to dislike_post_path(post), method: :put ,remote: true do %>
        <font size="20">&#x1F44E;</font>
          <span class="votedown" id="<%=post.id%>"><%= post.get_downvotes.size %></span>
    <% end %>
    </span>

    <div class="comment-holder" style="background-color: #eaeaea">
      <br><% post.comments.each do |comment| %>

          <img src = '<%=comment.user.image%>' height="30px" weight="30px" alt="no image"><font color="blue"><%=comment.user.name%></font>   <%=comment.comment%> <br>
      <%end%>
      </div>

      <form class="new_comment" data-remote="true" id="new_comment" action="/posts/<%=post.id %>/comments" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="nnicj7NUV/IlcShnylKnhisyLCDqiggvYSK8FeW+amZGHnG9WRQBHPNNZxPzCTxRISpK0GPqsBFxFUuVneci5w==" />
        <input type="hidden" name="comment[user_id]" value="<%=current_user.id%>">


        <div id="field" >
          <textarea name="comment[comment]" style="background-image:url(<%=current_user.image%>); background-size: 3% 100%" id="comment_comment" placeholder=" Write a comment..." >
</textarea>
        </div>

        <div class="btn">
          <input type="submit" name="commit" value="Comment" data-disable-with="Comment" />
        </div>
      </form>
      <hr>

    </tr>
      </section>
<% end %>


</section>

<!-- end of posts cards -->

ideasboardwithcss/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    This project was developed by Ranjith Dontamsetti
  </small>
  <nav>
    <ul>

      <li></li>
    </ul>
  </nav>
</footer>

ideasboardwithcss/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">

  <%= link_to "SU Kickstarter", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-left" style="width: 40%; padding-left: 10%">
      <% if current_user %>
      <%= form_tag home_viewAll_path, :method => 'get', :id => "posts_search" do %> <br/>
            <%= text_field_tag :search, params[:search] %> <input type="submit"  hidden>

      <% end %>
          <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">

        <% if current_user %>
            <li><%= link_to "Home", '/home/viewAll' %></li>
        <li><a><%= current_user.name %></a></li>
        <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>

        <% end %>


      </ul>
    </nav>
  </div>
</header>

ideasboardwithcss/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

ideasboardwithcss/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideasboardwithgoogle</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    <%= yield %>
    <%= render 'layouts/footer' %>

  </div>
  </body>
</html>

ideasboardwithcss/app/views/posts/_form.html.erb
<%= form_for([@post.user, @post]) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ideasboardwithcss/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', [@post.user, @post] %> |
<%= link_to 'Back', user_posts_path(@post.user) %>

ideasboardwithcss/app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= link_to 'Show', [post.user, post] %></td>
    <td><%= link_to 'Edit', edit_user_post_path(post.user, post) %></td>
    <td><%= link_to 'Destroy', [post.user, post], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

ideasboardwithcss/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', user_posts_path(@post.user) %>

ideasboardwithcss/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>


<%= link_to 'Edit', edit_user_post_path(@post.user, @post) %> |
<%= link_to 'Back', user_posts_path(@post.user) %>